AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Twitch eventsub handlers

Parameters:
  GoLiveWebhookUrl:
    Type: String
    Description: >
      The url of the Discord webhook to trigger when the go-live event is fired
  GoLiveMessage:
    Type: String
    Description: >
      The message to post when this webhook is triggered

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x
    CodeUri: .
    Architectures:
      - x86_64


Resources:
  GoLiveFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: src/app.goLiveHandler
      Events:
        GoLive:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /go-live
            Method: post
      Environment:
        Variables:
          DISCORD_GO_LIVE_WEBHOOK: !Ref GoLiveWebhookUrl
          GO_LIVE_MESSAGE: !Ref GoLiveMessage
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
        - src/app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  APIBaseUrl:
    Description: "API Gateway endpoint URL for Prod stage functions"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  GoLiveFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt GoLiveFunction.Arn
  GoLiveFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt GoLiveFunctionRole.Arn
